// Country code to flag emoji mapping
export const countryCodeFlags: {
  [key: string]: { flag: string; country: string };
} = {
  "+1": { flag: "🇺🇸", country: "USA" },
  "+7": { flag: "🇷🇺", country: "Russia" },
  "+20": { flag: "🇪🇬", country: "Egypt" },
  "+27": { flag: "🇿🇦", country: "South Africa" },
  "+30": { flag: "🇬🇷", country: "Greece" },
  "+31": { flag: "🇳🇱", country: "Netherlands" },
  "+32": { flag: "🇧🇪", country: "Belgium" },
  "+33": { flag: "🇫🇷", country: "France" },
  "+34": { flag: "🇪🇸", country: "Spain" },
  "+36": { flag: "🇭🇺", country: "Hungary" },
  "+39": { flag: "🇮🇹", country: "Italy" },
  "+40": { flag: "🇷🇴", country: "Romania" },
  "+41": { flag: "🇨🇭", country: "Switzerland" },
  "+43": { flag: "🇦🇹", country: "Austria" },
  "+44": { flag: "🇬🇧", country: "UK" },
  "+45": { flag: "🇩🇰", country: "Denmark" },
  "+46": { flag: "🇸🇪", country: "Sweden" },
  "+47": { flag: "🇳🇴", country: "Norway" },
  "+48": { flag: "🇵🇱", country: "Poland" },
  "+49": { flag: "🇩🇪", country: "Germany" },
  "+51": { flag: "🇵🇪", country: "Peru" },
  "+52": { flag: "🇲🇽", country: "Mexico" },
  "+53": { flag: "🇨🇺", country: "Cuba" },
  "+54": { flag: "🇦🇷", country: "Argentina" },
  "+55": { flag: "🇧🇷", country: "Brazil" },
  "+56": { flag: "🇨🇱", country: "Chile" },
  "+57": { flag: "🇨🇴", country: "Colombia" },
  "+58": { flag: "🇻🇪", country: "Venezuela" },
  "+60": { flag: "🇲🇾", country: "Malaysia" },
  "+61": { flag: "🇦🇺", country: "Australia" },
  "+62": { flag: "🇮🇩", country: "Indonesia" },
  "+63": { flag: "🇵🇭", country: "Philippines" },
  "+64": { flag: "🇳🇿", country: "New Zealand" },
  "+65": { flag: "🇸🇬", country: "Singapore" },
  "+66": { flag: "🇹🇭", country: "Thailand" },
  "+81": { flag: "🇯🇵", country: "Japan" },
  "+82": { flag: "🇰🇷", country: "South Korea" },
  "+84": { flag: "🇻🇳", country: "Vietnam" },
  "+86": { flag: "🇨🇳", country: "China" },
  "+90": { flag: "🇹🇷", country: "Turkey" },
  "+91": { flag: "🇮🇳", country: "India" },
  "+92": { flag: "🇵🇰", country: "Pakistan" },
  "+93": { flag: "🇦🇫", country: "Afghanistan" },
  "+94": { flag: "🇱🇰", country: "Sri Lanka" },
  "+95": { flag: "🇲🇲", country: "Myanmar" },
  "+98": { flag: "🇮🇷", country: "Iran" },
  "+211": { flag: "🇸🇸", country: "South Sudan" },
  "+212": { flag: "🇲🇦", country: "Morocco" },
  "+213": { flag: "🇩🇿", country: "Algeria" },
  "+216": { flag: "🇹🇳", country: "Tunisia" },
  "+218": { flag: "🇱🇾", country: "Libya" },
  "+220": { flag: "🇬🇲", country: "Gambia" },
  "+221": { flag: "🇸🇳", country: "Senegal" },
  "+222": { flag: "🇲🇷", country: "Mauritania" },
  "+223": { flag: "🇲🇱", country: "Mali" },
  "+224": { flag: "🇬🇳", country: "Guinea" },
  "+225": { flag: "🇨🇮", country: "Ivory Coast" },
  "+226": { flag: "🇧🇫", country: "Burkina Faso" },
  "+227": { flag: "🇳🇪", country: "Niger" },
  "+228": { flag: "🇹🇬", country: "Togo" },
  "+229": { flag: "🇧🇯", country: "Benin" },
  "+230": { flag: "🇲🇺", country: "Mauritius" },
  "+231": { flag: "🇱🇷", country: "Liberia" },
  "+232": { flag: "🇸🇱", country: "Sierra Leone" },
  "+233": { flag: "🇬🇭", country: "Ghana" },
  "+234": { flag: "🇳🇬", country: "Nigeria" },
  "+235": { flag: "🇹🇩", country: "Chad" },
  "+236": { flag: "🇨🇫", country: "Central African Republic" },
  "+237": { flag: "🇨🇲", country: "Cameroon" },
  "+238": { flag: "🇨🇻", country: "Cape Verde" },
  "+239": { flag: "🇸🇹", country: "São Tomé and Príncipe" },
  "+240": { flag: "🇬🇶", country: "Equatorial Guinea" },
  "+241": { flag: "🇬🇦", country: "Gabon" },
  "+242": { flag: "🇨🇬", country: "Congo" },
  "+243": { flag: "🇨🇩", country: "DRC" },
  "+244": { flag: "🇦🇴", country: "Angola" },
  "+245": { flag: "🇬🇼", country: "Guinea-Bissau" },
  "+246": { flag: "🇮🇴", country: "British Indian Ocean" },
  "+248": { flag: "🇸🇨", country: "Seychelles" },
  "+249": { flag: "🇸🇩", country: "Sudan" },
  "+250": { flag: "🇷🇼", country: "Rwanda" },
  "+251": { flag: "🇪🇹", country: "Ethiopia" },
  "+252": { flag: "🇸🇴", country: "Somalia" },
  "+253": { flag: "🇩🇯", country: "Djibouti" },
  "+254": { flag: "🇰🇪", country: "Kenya" },
  "+255": { flag: "🇹🇿", country: "Tanzania" },
  "+256": { flag: "🇺🇬", country: "Uganda" },
  "+257": { flag: "🇧🇮", country: "Burundi" },
  "+258": { flag: "🇲🇿", country: "Mozambique" },
  "+260": { flag: "🇿🇲", country: "Zambia" },
  "+261": { flag: "🇲🇬", country: "Madagascar" },
  "+262": { flag: "🇷🇪", country: "Réunion" },
  "+263": { flag: "🇿🇼", country: "Zimbabwe" },
  "+264": { flag: "🇳🇦", country: "Namibia" },
  "+265": { flag: "🇲🇼", country: "Malawi" },
  "+266": { flag: "🇱🇸", country: "Lesotho" },
  "+267": { flag: "🇧🇼", country: "Botswana" },
  "+268": { flag: "🇸🇿", country: "Eswatini" },
  "+269": { flag: "🇰🇲", country: "Comoros" },
  "+880": { flag: "🇧🇩", country: "Bangladesh" },
  "+960": { flag: "🇲🇻", country: "Maldives" },
  "+961": { flag: "🇱🇧", country: "Lebanon" },
  "+962": { flag: "🇯🇴", country: "Jordan" },
  "+963": { flag: "🇸🇾", country: "Syria" },
  "+964": { flag: "🇮🇶", country: "Iraq" },
  "+965": { flag: "🇰🇼", country: "Kuwait" },
  "+966": { flag: "🇸🇦", country: "Saudi Arabia" },
  "+967": { flag: "🇾🇪", country: "Yemen" },
  "+968": { flag: "🇴🇲", country: "Oman" },
  "+971": { flag: "🇦🇪", country: "UAE" },
  "+972": { flag: "🇮🇱", country: "Israel" },
  "+973": { flag: "🇧🇭", country: "Bahrain" },
  "+974": { flag: "🇶🇦", country: "Qatar" },
  "+975": { flag: "🇧🇹", country: "Bhutan" },
  "+976": { flag: "🇲🇳", country: "Mongolia" },
  "+977": { flag: "🇳🇵", country: "Nepal" },
  "+992": { flag: "🇹🇯", country: "Tajikistan" },
  "+993": { flag: "🇹🇲", country: "Turkmenistan" },
  "+994": { flag: "🇦🇿", country: "Azerbaijan" },
  "+995": { flag: "🇬🇪", country: "Georgia" },
  "+996": { flag: "🇰🇬", country: "Kyrgyzstan" },
  "+998": { flag: "🇺🇿", country: "Uzbekistan" },
};

// Phone number patterns for auto-detection
export const phonePatterns = [
  { code: "+1", pattern: /^(\+?1)?[2-9]\d{2}[2-9]\d{6}$/, name: "USA/Canada" },
  { code: "+44", pattern: /^(\+?44)?[1-9]\d{9,10}$/, name: "UK" },
  { code: "+33", pattern: /^(\+?33)?[1-9]\d{8}$/, name: "France" },
  { code: "+49", pattern: /^(\+?49)?[1-9]\d{7,11}$/, name: "Germany" },
  { code: "+39", pattern: /^(\+?39)?[0-9]{6,10}$/, name: "Italy" },
  { code: "+34", pattern: /^(\+?34)?[6-9]\d{8}$/, name: "Spain" },
  { code: "+31", pattern: /^(\+?31)?[1-9]\d{8}$/, name: "Netherlands" },
  { code: "+32", pattern: /^(\+?32)?[1-9]\d{8,9}$/, name: "Belgium" },
  { code: "+41", pattern: /^(\+?41)?[1-9]\d{8}$/, name: "Switzerland" },
  { code: "+880", pattern: /^(\+?880)?1[3-9]\d{8}$/, name: "Bangladesh" },
  { code: "+91", pattern: /^(\+?91)?[6-9]\d{9}$/, name: "India" },
  { code: "+86", pattern: /^(\+?86)?1[3-9]\d{9}$/, name: "China" },
  { code: "+81", pattern: /^(\+?81)?[1-9]\d{1,4}\d{1,4}\d{4}$/, name: "Japan" },
  { code: "+234", pattern: /^(\+?234)?[0-9]{10}$/, name: "Nigeria" },
  { code: "+27", pattern: /^(\+?27)?[1-9]\d{8}$/, name: "South Africa" },
];
