const africanArchitectureRegions = [
  {
    title: "east-african-architecture",
    countries: [
      "Kenya",
      "Tanzania",
      "Uganda",
      "Ethiopia",
      "Somalia",
      "Burundi",
      "Rwanda",
      "Djibouti",
      "Comoros",
      "Eritrea",
      "Seychelles",
      "Mauritius",
      "South Sudan",
      "Réunion",
      "Mayotte",
      "French Southern and Antarctic Lands",
    ],
  },
  {
    title: "central-african-architecture",
    countries: [
      "Cameroon",
      "Equatorial Guinea",
      "Gabon",
      "Republic of the Congo",
      "Chad",
      "Congo",
      "Central African Republic",
      "Democratic Republic of the Congo",
      "São Tomé and Príncipe",
    ],
  },
  {
    title: "west-african-architecture",
    countries: [
      "Nigeria",
      "Niger",
      "Burkina Faso",
      "Benin",
      "Liberia",
      "Ghana",
      "The Gambia",
      "Mali",
      "Côte d'Ivoire",
      "Senegal",
      "Guinea",
      "Togo",
      "Sierra Leone",
      "Guinea-Bissau",
      "Mauritania",
      "Cape Verde",
      "Saint Helena",
      "Ascension Island",
      "Tristan da Cunha",
    ],
  },
  {
    title: "south-african-architecture",
    countries: [
      "South Africa",
      "Botswana",
      "Namibia",
      "Lesotho",
      "Eswatini",
      "Zimbabwe",
      "Zambia",
      "Mozambique",
      "Angola",
      "Malawi",
      "Madagascar",
    ],
  },
  {
    title: "north-african-architecture",
    countries: [
      "Algeria",
      "Egypt",
      "Libya",
      "Morocco",
      "Tunisia",
      "Western Sahara",
      "Sudan",
    ],
  },
  {
    title: "global-african-architecture",
    countries: [
      "Afghanistan",
      "Albania",
      "Andorra",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Brazil",
      "Brunei",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "East Timor",
      "Ecuador",
      "El Salvador",
      "Estonia",
      "Fiji",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kiribati",
      "North Korea",
      "South Korea",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macedonia",
      "Malaysia",
      "Maldives",
      "Malta",
      "Marshall Islands",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Myanmar",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russia",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Saudi Arabia",
      "Serbia",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Spain",
      "Sri Lanka",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Thailand",
      "Tonga",
      "Trinidad and Tobago",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City",
      "Venezuela",
      "Vietnam",
      "Yemen",
    ],
  },
];

export default africanArchitectureRegions;
